chapter2/mysite/blog/urls.py
from django.urls import path
from .views import post_list, post_detail, post_share

app_name = 'blog'

urlpatterns = [
    # post views
     path('', post_list, name='post_list'),
     path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         post_detail,
         name='post_detail'),
     path('<int:post_id>/share/',
         post_share, name='post_share'),
     path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
]

chapter2/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),

]

chapter2/mysite/blog/models.py
from django.db import models
# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    tags = TaggableManager()
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,  unique_for_date='publish')
    author = models.ForeignKey(
        User,  on_delete=models.CASCADE,  related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,  choices=STATUS_CHOICES, default='draft')
    visits = models.PositiveIntegerField(default=0)
    summary = models.TextField(default="", max_length=500)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

chapter2/mysite/shop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Shop(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,  unique_for_date='publish')
    user = models.ForeignKey(User,  on_delete=models.CASCADE,  related_name='shop_posts')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

chapter2/mysite/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

chapter2/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count


def post_list(request,  tag_slug=None):
    object_list = Post.objects.filter(status='published')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 2)  # 3 posts in each page
    try:
        page = request.GET.get('page')
    except:
        page = 1
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    post.visits = post.visits + 1
    post.save()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts
                   })


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ... send email
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

chapter2/mysite/shop/views.py
from django.shortcuts import render

# Create your views here.

chapter2/mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static  'css/blog.css' %}" rel="stylesheet">
</head>

<body dir=rtl>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog.</p>
    </div>
</body>

</html>

chapter2/mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }} - Visits : {{post.visits}}
</p>
{% with comments.count as total_comments %}
<h2>
تعداد نظرات : {{ total_comments }} 
</h2>
{% endwith %}

<p>
خلاصه : 
<br/>
{{post.summary}}
</p>
<hr/>
{{ post.body|linebreaks }}
<hr>
<p>
<a href="{% url "blog:post_share" post.id %}">
این نوشته را با دوستانتان به اشتراک بگذارید
</a>
</p>
<h2>مطالب مشابه</h2>
{% for post in similar_posts %}
<p>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
مطلب مشابهی در حال حاضر وجود ندارد
{% endfor %}
<hr/>
<h2>نظرات</h2>
<br/>
{% for comment in comments %}
<div class="comment">
<p class="info">
نظر شماره {{ forloop.counter }} توسط {{ comment.name }}
{{ comment.created }}
</p>
{{ comment.body|linebreaks }}
</div>
{% empty %}
<p>هیچ نظری تاکنون ثبت نشده است.</p>
{% endfor %}

{% if new_comment %}
<h2>نظر شما با موفقیت ثبت شد</h2>
{% else %}
<h2>ارسال نظر</h2>
<form method="post">
{{ comment_form.as_p }}
{% csrf_token %}
<p><input type="submit" value="Add comment"></p>
</form>
{% endif %}

{% endblock %}

chapter2/mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}Post List{% endblock %}
{% block content %}
<h1>دل‌نوشته‌ها</h1>
{% if tag %}
    <h2>فهرست پستهای حاوی  "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
<p class="tags">
برچسب‌ها: 

    {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
        {{ tag.name }}
        </a>
        {% if not forloop.last %},
        {% endif %}
    {% endfor %}

</p>
<hr>
<h6>visits : <b><i> {{post.visits}} </i></b> </h6>
{{ post.body|truncatewords:50|linebreaks }}
<hr>
{% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

chapter2/mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
    {{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
    {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
    {% comment %} {{ form.as_p }} {% endcomment %}
    <p>
نام ارسال کننده :
    {{ form.name}}
    </p>
    <p>
    ایمیل :
    {{ form.email}}
    </p>
    <p>
    شخص دریافت کننده :
    {{ form.to}}
    </p>
    <p>
    توضیحات :
    {{ form.comments}}
</p>

    {% csrf_token %}
    <input type="submit" value="Send e-mail">
    </form>
    {% endif %}
{% endblock %}

chapter2/mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>